package Test;

import DAO.BrandDAO;
import DAO.JdbcBrandDAO;
import Model.Brand;
import Service.BrandService;
import db.DatabaseManager;
import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class BrandServiceTest {

    private static Connection connection;
    private static BrandService brandService;
    private static int testBrandId;

    @BeforeAll
    static void setup() throws Exception {
        connection = DatabaseManager.getInstance().getConnection();
        BrandDAO brandDAO = new JdbcBrandDAO();
        brandService = new BrandService(brandDAO.toString());
    }

    @AfterAll
    static void teardown() throws Exception {
        if (testBrandId > 0) {
            String deleteBrand = "DELETE FROM brand WHERE brand_id=?";
            try (PreparedStatement ps = connection.prepareStatement(deleteBrand)) {
                ps.setInt(1, testBrandId);
                ps.executeUpdate();
            }
        }
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }

    private Brand createTestBrand() {
        return new Brand("Test Brand");
    }

    @Test
    void testCreateBrand() {
        Brand brand = createTestBrand();
        brandService.createBrand(brand);

        assertTrue(brand.getBrandId() > 0, "Brand ID should be generated by the DB");
        testBrandId = brand.getBrandId(); // ruaj për cleanup
    }

    @Test
    void testGetBrandById() {
        Brand brand = createTestBrand();
        brandService.createBrand(brand);

        Optional<Brand> retrieved = brandService.getBrandById(brand.getBrandId());
        assertTrue(retrieved.isPresent());
        assertEquals(brand.getName(), retrieved.get().getName());
    }

    @Test
    void testUpdateBrand() {
        Brand brand = createTestBrand();
        brandService.createBrand(brand);

        brand.setName("Updated Brand Name");
        boolean updated = brandService.updateBrand(brand);
        assertTrue(updated);

        Optional<Brand> retrieved = brandService.getBrandById(brand.getBrandId());
        assertTrue(retrieved.isPresent());
        assertEquals("Updated Brand Name", retrieved.get().getName());
    }

    @Test
    void testGetAllBrands() {
        Brand brand1 = createTestBrand();
        Brand brand2 = new Brand("Another Brand");

        brandService.createBrand(brand1);
        brandService.createBrand(brand2);

        List<Brand> brands = brandService.getAllBrands();
        assertTrue(brands.size() >= 2);
    }

    @Test
    void testDeleteBrand() {
        Brand brand = createTestBrand();
        brandService.createBrand(brand);

        boolean deleted = brandService.deleteBrand(brand.getBrandId());
        assertTrue(deleted);

        Optional<Brand> retrieved = brandService.getBrandById(brand.getBrandId());
        assertFalse(retrieved.isPresent());
    }
}
