package Test;

import DAO.ItemDAO;
import DAO.JdbcItemDAO;
import Model.Item;
import Service.ItemService;
import db.DatabaseManager;
import org.junit.jupiter.api.*;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class ItemServiceTest {

    private static Connection connection;
    private static ItemService itemService;
    private static int testUserId;

    @BeforeAll
    static void setup() throws Exception {
        connection = DatabaseManager.getConnection();
        ItemDAO itemDAO = new JdbcItemDAO(connection);
        itemService = new ItemService(itemDAO);

        String insertUser = "INSERT INTO user (name, password, email) VALUES (?, ?, ?)";
        try (PreparedStatement ps = connection.prepareStatement(insertUser, PreparedStatement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, "Test User");
            ps.setString(2, "password123");
            ps.setString(3, "testuser@example.com");
            ps.executeUpdate();
            var rs = ps.getGeneratedKeys();
            if (rs.next()) testUserId = rs.getInt(1);
        }
    }

    @AfterAll
    static void teardown() throws Exception {
        String deleteUser = "DELETE FROM user WHERE user_id=?";
        try (PreparedStatement ps = connection.prepareStatement(deleteUser)) {
            ps.setInt(1, testUserId);
            ps.executeUpdate();
        }
        if (connection != null && !connection.isClosed()) connection.close();
    }

    private Item createTestItem() {
        return new Item(
                0,
                testUserId,
                null,
                null,
                "Test Item",
                "Item description",
                BigDecimal.valueOf(49.99),
                "M",
                "New",
                "test.jpg",
                "available",
                new Timestamp(System.currentTimeMillis())
        );
    }

    @Test
    void testCreateItem() {
        Item item = createTestItem();
        itemService.createItem(item);
        assertTrue(item.getItemId() > 0, "Item ID should be generated by the DB");
    }

    @Test
    void testGetItemById() {
        Item item = createTestItem();
        itemService.createItem(item);

        Optional<Item> retrieved = itemService.getItemById(item.getItemId());
        assertTrue(retrieved.isPresent());
        assertEquals(item.getTitle(), retrieved.get().getTitle());
    }

    @Test
    void testUpdateItem() {
        Item item = createTestItem();
        itemService.createItem(item);

        item.setTitle("Updated Title");
        boolean updated = itemService.updateItem(item);
        assertTrue(updated);

        Optional<Item> retrieved = itemService.getItemById(item.getItemId());
        assertTrue(retrieved.isPresent());
        assertEquals("Updated Title", retrieved.get().getTitle());
    }

    @Test
    void testGetAllItems() {
        Item item1 = createTestItem();
        Item item2 = createTestItem();
        itemService.createItem(item1);
        itemService.createItem(item2);

        List<Item> items = itemService.getAllItems();
        assertTrue(items.size() >= 2);
    }

    @Test
    void testMarkItemAsSold() {
        Item item = createTestItem();
        itemService.createItem(item);

        boolean marked = itemService.markItemAsSold(item.getItemId());
        assertTrue(marked);

        Optional<Item> retrieved = itemService.getItemById(item.getItemId());
        assertTrue(retrieved.isPresent());
        assertEquals("sold", retrieved.get().getStatus());
    }

    @Test
    void testGetItemsByStatus() {
        Item item = createTestItem();
        itemService.createItem(item);

        List<Item> availableItems = itemService.getItemsByStatus("available");
        assertTrue(availableItems.stream().anyMatch(i -> i.getItemId() == item.getItemId()));
    }

    @Test
    void testDeleteItem() {
        Item item = createTestItem();
        itemService.createItem(item);

        boolean deleted = itemService.deleteItem(item.getItemId());
        assertTrue(deleted);

        Optional<Item> retrieved = itemService.getItemById(item.getItemId());
        assertFalse(retrieved.isPresent());
    }

    @Test
    void testGetItemsByUser() {
        Item item = createTestItem();
        itemService.createItem(item);

        List<Item> items = itemService.getItemsByUser(testUserId);
        assertTrue(items.stream().anyMatch(i -> i.getItemId() == item.getItemId()));
    }
}
